### ISSUE TITLE
Prevent invalid labels

### ISSUE THREAD

**Issue by xoxys** [promhippie/prometheus-hcloud-sd#16]
Hetzner Cloud allows using `.`, `-` and `_` in labels. While underscores works as expected, labels containing the other two chars, especially used in the key of a label, results in an "invalid label error" e.g.  a label `a.b.c:example` results in `__meta_hcloud_label_a.b.c="example"`. Maybe a simple replace logic should be used to prevent invalid labels.

**Comment by tboerger** [comment]
v0.4.2 including a fix is getting built now.

**Comment by xoxys** [comment]
Youre welcome...
